### ISSUE TITLE
Image Segmentation application

### ISSUE THREAD

**Issue by tribhuvanesh** [dalab/dissolve-struct#13]
Create a demonstration of Dissolve in the context of Image Segmentation, beginning with the MSRC dataset.

#### The plan
![Image Segmentation plan](https://dl.dropboxusercontent.com/u/12851272/2014-11-20%2015.08.56.jpg)

#### Components
1. Loading images
2. Feature Function
3. Loss Function
4. Oracle Function using Factorie

**Comment by lmiroslaw** [comment]
This application is interesting. Is there a paper that describes this approach?

**Comment by tribhuvanesh** [comment]
Hi Lukasz!




That’s in progress. :)




You could meanwhile checkout a mini-description at:

http://dalab.github.io/dissolve-struct/#image-segmentation-using-crfs




Or the code itself:

https://github.com/dalab/dissolve-struct/blob/tuning/dissolve-struct-examples/src/main/scala/ch/ethz/dalab/dissolve/examples/imageseg/ImageSegmentationDemo.scala




We’ll be glad to help you out in case you need more details!




Thanks,

Tribhu




—
Tribhuvanesh Orekondy
