### ISSUE TITLE
add user-friendly diagnostic checks for the provided decoding oracles

### ISSUE THREAD

**Issue by martinjaggi** [dalab/dissolve-struct#23]
we should very soon add simple checks of any candidate oracles provided by the user.
this checks are to verify that the oracle does not have obvious flaws, and is compatible with the used feature vector which the user has provided. another goal is to verify that it does the loss-augmentation correctly.

such simple checks can avoid many problems later, such as negative duality gaps etc, and would improve the usability of structured SVMs greatly for all users.

here are some simple checks, i'm sure i missed many other possible ones.
* pick w = all ones, or minus that, or some random signs, or some random w vector
* pick a random data example (or do the following for all examples)
  1. decoding (without loss term) (of that example at w) must return something which has an inner product at least better than zero
  2. decoding (with loss augmentation) must return something y which has an inner product at least better than the error term of that y.
  3. sample a bunch of random y labels. the answer by the oracle should be at least as good as all these.
(none of this checks should depend on a distributed setting. these can be run on one machine, before the actual optimization).

these are easy to implement. however, depending if the user claims to have an exact oracle or approximate one, the warnings should sound a bit different if the above is violated...

as the dissolve library will support using several oracles at once soon, it should also know which ones are  (claimed to be) exact or not.
for example many diagnostics, such as the structured SVM primal objective, or duality gap, do require an exact oracle. if it's not available, the user should be aware of it, or we should better output a warning.

**Comment by tribhuvanesh** [comment]
The diagnostic tool is now available [here](https://github.com/dalab/dissolve-struct/tree/oracle-stream/dissolve-struct-examples/src/test/scala/ch/ethz/dalab/dissolve/diagnostics).
Will continue adding more unit-tests as and when we can think of one.
